name: simgnn
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2024.12.14
  - certifi=2021.5.30
  - decorator=5.1.1
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libzlib=1.3.1
  - ncurses=6.5
  - networkx=2.4
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1w
  - pandas=0.23.4
  - pip=21.2.2
  - python=3.6.15
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.3
  - readline=8.2
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.47.2
  - texttable=1.5.0
  - tk=8.6.13
  - tqdm=4.28.1
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.3.1
  - pip:
      - argparse==1.1
      - charset-normalizer==2.0.12
      - dataclasses==0.8
      - googledrivedownloader==0.4
      - idna==3.10
      - isodate==0.6.1
      - jinja2==3.0.3
      - markupsafe==2.0.1
      - pillow==8.4.0
      - pyparsing==3.1.4
      - pyyaml==6.0.1
      - rdflib==5.0.0
      - requests==2.27.1
      - torch==1.10.0+cu113
      - torch-cluster==1.5.9
      - torch-geometric==2.0.3
      - torch-scatter==2.0.9
      - torch-sparse==0.6.12
      - torchvision==0.11.1+cu113
      - typing-extensions==4.1.1
      - urllib3==1.26.20
      - yacs==0.1.8
#pip install torch==1.10.0+cu113 torchvision==0.11.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
#pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
#pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
#pip install torch-cluster -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
#pip install torch-geometric